# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "071c9rgad2gan0gyihfphsl60amxs8zcwcsi09zwyxx0mlqcdvpz";
    x86_64-linux = "0pvrhwm2ck3c9qyzav7nswy4jdfvrqll3jvm9f23yxj5ldhn8627";
    armv7l-linux = "1ag2wr7m5s9djyqp5bbz2nhpd1wwdsn8hy8gb35sgna4d8lz3y3y";
    aarch64-linux = "1ilqmvr7mzcz9wyy3n7p239b5hqaz8m45wz0rvlxm6xcv6fgisx6";
    x86_64-darwin = "068y9bav5x65cy9wmpg6cpld14v07k149v3cbxbbp14b5zinnlzr";
    aarch64-darwin = "0dfbzdqcnnjc9qqa48z1jakdlc5q09lfyav1spj138w92m0f7y07";
  };

  urlMap = {
    i686-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.4/moon_0.19.4_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.4/moon_0.19.4_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.4/moon_0.19.4_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.4/moon_0.19.4_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.4/moon_0.19.4_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.4/moon_0.19.4_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "moon_0.19.4_Linux_i386";
    x86_64-linux = "moon_0.19.4_Linux_x86_64";
    armv7l-linux = "moon_0.19.4_Linux_armv7";
    aarch64-linux = "moon_0.19.4_Linux_arm64";
    x86_64-darwin = "moon_0.19.4_Darwin_x86_64";
    aarch64-darwin = "moon_0.19.4_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "moon";
  version = "0.19.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./moon $out/bin/moon
    installManPage ./manpages/moon.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful game development AI agent that can build complete games from scratch. Expert in Unity, Unreal Engine, and Godot.";
    homepage = "https://moonforge.com";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
