# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0j12g3s0rkg38g36v6pknqn02j7qd8bqs5cq7g5k30hdv8dlznrd";
    x86_64-linux = "1yzgbaggqvgb75yb7h4bb2qlkv0ljp9hmzpq2md1i872jycb2vdc";
    armv7l-linux = "1jk7zyllql56f43afaxn9pfkykf8ssjinr5xkif7v92yc0d27n5i";
    aarch64-linux = "0bg3gb3l6q9pcq3rqsi986g84dzcwl8dga7zp3a14frmgcrkl439";
    x86_64-darwin = "0jgrpn0jh02iwhljdprhksy3a0mddk8isdglvm8lb4clc6q76kaq";
    aarch64-darwin = "08lql9h9fis4kmxsvpdqyxwjnjkdak5qb1qh3kmrykxfml9wxdjh";
  };

  urlMap = {
    i686-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "moon_0.19.1_Linux_i386";
    x86_64-linux = "moon_0.19.1_Linux_x86_64";
    armv7l-linux = "moon_0.19.1_Linux_armv7";
    aarch64-linux = "moon_0.19.1_Linux_arm64";
    x86_64-darwin = "moon_0.19.1_Darwin_x86_64";
    aarch64-darwin = "moon_0.19.1_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "moon";
  version = "0.19.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./moon $out/bin/moon
    installManPage ./manpages/moon.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful game development AI agent that can build complete games from scratch. Expert in Unity, Unreal Engine, and Godot.";
    homepage = "https://moonforge.com";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
