# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "01nxcwbcm71ldqz0li9ckadc4ycf6g5n6rwwb0wfc3kavghvk2a9";
    x86_64-linux = "1apm5vgk3qa1rjq8s0856x6h07kaxvj8wj4ww7p5jzbykiya5zc1";
    armv7l-linux = "1g967zhzdn3821dmmskh80l48zh5v8gkwxpf6l4gp2sy1ayhzcdv";
    aarch64-linux = "0ldjpdv055jcc0z8wp72l2ixvlhh181a2dw8iklnshwdns9bg62k";
    x86_64-darwin = "1hszq5hjbnrv2gy9jci3l304zp2ngbjydg0hf4ilkq0mvg8al4hp";
    aarch64-darwin = "1kd21bmilzak5c0b8wi0d2llqdqqjrzwa4bqwi04bs69gfw9mkzs";
  };

  urlMap = {
    i686-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.20.2/moon_0.20.2_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.20.2/moon_0.20.2_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.20.2/moon_0.20.2_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/MoonForgeAI/moon/releases/download/v0.20.2/moon_0.20.2_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/MoonForgeAI/moon/releases/download/v0.20.2/moon_0.20.2_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/MoonForgeAI/moon/releases/download/v0.20.2/moon_0.20.2_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "moon_0.20.2_Linux_i386";
    x86_64-linux = "moon_0.20.2_Linux_x86_64";
    armv7l-linux = "moon_0.20.2_Linux_armv7";
    aarch64-linux = "moon_0.20.2_Linux_arm64";
    x86_64-darwin = "moon_0.20.2_Darwin_x86_64";
    aarch64-darwin = "moon_0.20.2_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "moon";
  version = "0.20.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./moon $out/bin/moon
    installManPage ./manpages/moon.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "A powerful game development AI agent that can build complete games from scratch. Expert in Unity, Unreal Engine, and Godot.";
    homepage = "https://moonforge.com";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
